# -*- coding: utf-8 -*-
"""analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PRf7Ai-2r1INiWplC5HwTpWHLlH_XDl9
"""

import pandas as pd
import matplotlib.pyplot as plt

# Read messages from the Kafka consumer and create a pandas DataFrame
messages = []
for message in consumer:
    data = json.loads(message.value.decode('utf-8'))
    messages.append(data)
df = pd.DataFrame(messages)

# Convert the transaction time to a pandas datetime object
df['transaction_time'] = pd.to_datetime(df['transaction_time'])

# Group the transactions by hour and sum the transaction amounts
grouped = df.groupby(pd.Grouper(key='transaction_time', freq='H'))['transaction_amount'].sum()

# Create a bar chart showing the total transaction amounts by hour
plt.bar(grouped.index, grouped.values)
plt.xlabel('Hour')
plt.ylabel('Total Transaction Amount')
plt.show()