# -*- coding: utf-8 -*-
"""consumer.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17ZbVsJiRPT8HCceCHrplIkq8wOUm7U7d
"""

from kafka import KafkaConsumer
import json

# Create a Kafka consumer instance
consumer = KafkaConsumer('mobile-money-transactions', bootstrap_servers=['localhost:9092'], auto_offset_reset='earliest')

# Read messages from the Kafka cluster and process them
for message in consumer:
    # Convert the message to a JSON object
    data = json.loads(message.value.decode('utf-8'))