# -*- coding: utf-8 -*-
"""producer.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G-y847WFJVS8paDabflLLM3bBYePHqUr
"""

from kafka import KafkaProducer
import json

# Create a Kafka producer instance
producer = KafkaProducer(bootstrap_servers=['localhost:9092'])

# Define the topic to send messages to
topic = 'mobile-money-transactions'

# Read data from a file and send it to the Kafka cluster
with open('transactions.json', 'r') as f:
    for line in f:
        # Convert each line to a JSON object
        data = json.loads(line)
        # Send the data to the Kafka cluster
        producer.send(topic, value=json.dumps(data).encode('utf-8'))